### ISSUE TITLE
Add autoprefixer

### ISSUE THREAD

**Issue by stophecom** [frontale-festival/frontale-festival.github.io#7]
Like this https://libraries.io/bower/grunt-autoprefixer ?

**Comment by njam** [comment]
@christopheschwyzer it's already there as a plugin to the less grunt task:

```
    less: {
      all: {
        options: {
          sourceMap: true,
          outputSourceFiles: true,
          sourceMapURL: '<%= pkg.name %>.css.map',
          plugins: [
            new (require('less-plugin-autoprefix'))({browsers: ['last 2 versions']})
          ]
        },
        files: {
          "dist/<%= pkg.name %>.css": "css/main.less"
        }
      }
    },
```

I see prefixes being added (for example `-webkit`). Is something specific missing?

**Comment by stophecom** [comment]
Oh you're right - I didn't even check ;) It's a different problem with `flexbox` in IE. Will check.
